package com.corecto.web.model.pojo.extra;

// Generated 11-nov-2013 20:22:20 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * AnotomiaPatologica generated by hbm2java
 */
public class AnotomiaPatologica implements java.io.Serializable {

	private long idanotomia;
	private Consulta consulta;
	private String biopsia;
	private Date fechaDiag;
	private String diagHistologico;
	private String apSugestiva;
	private String ihq;
	private String expresionConserv;
	private String diagnosticadoEn;
	private String gradoDif;
	private String baseDiagCirugia;
	private String baseDiag;

	public AnotomiaPatologica() {
	}

	public AnotomiaPatologica(long idanotomia) {
		this.idanotomia = idanotomia;
	}

	public AnotomiaPatologica(long idanotomia, Consulta consulta,
			String biopsia, Date fechaDiag, String diagHistologico,
			String apSugestiva, String ihq, String expresionConserv,
			String diagnosticadoEn, String gradoDif, String baseDiagCirugia,
			String baseDiag) {
		this.idanotomia = idanotomia;
		this.consulta = consulta;
		this.biopsia = biopsia;
		this.fechaDiag = fechaDiag;
		this.diagHistologico = diagHistologico;
		this.apSugestiva = apSugestiva;
		this.ihq = ihq;
		this.expresionConserv = expresionConserv;
		this.diagnosticadoEn = diagnosticadoEn;
		this.gradoDif = gradoDif;
		this.baseDiagCirugia = baseDiagCirugia;
		this.baseDiag = baseDiag;
	}

	public long getIdanotomia() {
		return this.idanotomia;
	}

	public void setIdanotomia(long idanotomia) {
		this.idanotomia = idanotomia;
	}

	public Consulta getConsulta() {
		return this.consulta;
	}

	public void setConsulta(Consulta consulta) {
		this.consulta = consulta;
	}

	public String getBiopsia() {
		return this.biopsia;
	}

	public void setBiopsia(String biopsia) {
		this.biopsia = biopsia;
	}

	public Date getFechaDiag() {
		return this.fechaDiag;
	}

	public void setFechaDiag(Date fechaDiag) {
		this.fechaDiag = fechaDiag;
	}

	public String getDiagHistologico() {
		return this.diagHistologico;
	}

	public void setDiagHistologico(String diagHistologico) {
		this.diagHistologico = diagHistologico;
	}

	public String getApSugestiva() {
		return this.apSugestiva;
	}

	public void setApSugestiva(String apSugestiva) {
		this.apSugestiva = apSugestiva;
	}

	public String getIhq() {
		return this.ihq;
	}

	public void setIhq(String ihq) {
		this.ihq = ihq;
	}

	public String getExpresionConserv() {
		return this.expresionConserv;
	}

	public void setExpresionConserv(String expresionConserv) {
		this.expresionConserv = expresionConserv;
	}

	public String getDiagnosticadoEn() {
		return this.diagnosticadoEn;
	}

	public void setDiagnosticadoEn(String diagnosticadoEn) {
		this.diagnosticadoEn = diagnosticadoEn;
	}

	public String getGradoDif() {
		return this.gradoDif;
	}

	public void setGradoDif(String gradoDif) {
		this.gradoDif = gradoDif;
	}

	public String getBaseDiagCirugia() {
		return this.baseDiagCirugia;
	}

	public void setBaseDiagCirugia(String baseDiagCirugia) {
		this.baseDiagCirugia = baseDiagCirugia;
	}

	public String getBaseDiag() {
		return this.baseDiag;
	}

	public void setBaseDiag(String baseDiag) {
		this.baseDiag = baseDiag;
	}

}
