package com.corecto.web.model.pojo.extra;

// Generated 11-nov-2013 20:22:20 by Hibernate Tools 3.4.0.CR1

/**
 * Antecedentes generated by hbm2java
 */
public class Antecedentes implements java.io.Serializable {

	private long idantecedente;
	private Consulta consulta;
	private String personales;
	private String personalesPatologicos;
	private String neoplasia;
	private String familiarCancer;
	private String antecedentesCcrh;

	public Antecedentes() {
	}

	public Antecedentes(long idantecedente) {
		this.idantecedente = idantecedente;
	}

	public Antecedentes(long idantecedente, Consulta consulta,
			String personales, String personalesPatologicos, String neoplasia,
			String familiarCancer, String antecedentesCcrh) {
		this.idantecedente = idantecedente;
		this.consulta = consulta;
		this.personales = personales;
		this.personalesPatologicos = personalesPatologicos;
		this.neoplasia = neoplasia;
		this.familiarCancer = familiarCancer;
		this.antecedentesCcrh = antecedentesCcrh;
	}

	public long getIdantecedente() {
		return this.idantecedente;
	}

	public void setIdantecedente(long idantecedente) {
		this.idantecedente = idantecedente;
	}

	public Consulta getConsulta() {
		return this.consulta;
	}

	public void setConsulta(Consulta consulta) {
		this.consulta = consulta;
	}

	public String getPersonales() {
		return this.personales;
	}

	public void setPersonales(String personales) {
		this.personales = personales;
	}

	public String getPersonalesPatologicos() {
		return this.personalesPatologicos;
	}

	public void setPersonalesPatologicos(String personalesPatologicos) {
		this.personalesPatologicos = personalesPatologicos;
	}

	public String getNeoplasia() {
		return this.neoplasia;
	}

	public void setNeoplasia(String neoplasia) {
		this.neoplasia = neoplasia;
	}

	public String getFamiliarCancer() {
		return this.familiarCancer;
	}

	public void setFamiliarCancer(String familiarCancer) {
		this.familiarCancer = familiarCancer;
	}

	public String getAntecedentesCcrh() {
		return this.antecedentesCcrh;
	}

	public void setAntecedentesCcrh(String antecedentesCcrh) {
		this.antecedentesCcrh = antecedentesCcrh;
	}

}
