package com.corecto.web.model.pojo.extra;

// Generated 11-nov-2013 20:22:20 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * CatHospital generated by hbm2java
 */
public class CatHospital implements java.io.Serializable {

	private int idcathospital;
	private String nombre;
	private String direccion;
	private Boolean estado;
	private Set<Consulta> consultas = new HashSet<Consulta>(0);

	public CatHospital() {
	}

	public CatHospital(int idcathospital) {
		this.idcathospital = idcathospital;
	}

	public CatHospital(int idcathospital, String nombre, String direccion,
			Boolean estado, Set<Consulta> consultas) {
		this.idcathospital = idcathospital;
		this.nombre = nombre;
		this.direccion = direccion;
		this.estado = estado;
		this.consultas = consultas;
	}

	public int getIdcathospital() {
		return this.idcathospital;
	}

	public void setIdcathospital(int idcathospital) {
		this.idcathospital = idcathospital;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

	public Set<Consulta> getConsultas() {
		return this.consultas;
	}

	public void setConsultas(Set<Consulta> consultas) {
		this.consultas = consultas;
	}

}
