package com.corecto.web.model.pojo.extra;

// Generated 11-nov-2013 20:22:20 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ConductaPostNeo generated by hbm2java
 */
public class ConductaPostNeo implements java.io.Serializable {

	private long idconductapostneo;
	private Consulta consulta;
	private String cirugia;
	private String milesCilindrico;
	private String urgencia;
	private Date urgenciaFecha;
	private String cirujano;
	private String WS;
	private Date fechaInicio;

	public ConductaPostNeo() {
	}

	public ConductaPostNeo(long idconductapostneo) {
		this.idconductapostneo = idconductapostneo;
	}

	public ConductaPostNeo(long idconductapostneo, Consulta consulta,
			String cirugia, String milesCilindrico, String urgencia,
			Date urgenciaFecha, String cirujano, String WS, Date fechaInicio) {
		this.idconductapostneo = idconductapostneo;
		this.consulta = consulta;
		this.cirugia = cirugia;
		this.milesCilindrico = milesCilindrico;
		this.urgencia = urgencia;
		this.urgenciaFecha = urgenciaFecha;
		this.cirujano = cirujano;
		this.WS = WS;
		this.fechaInicio = fechaInicio;
	}

	public long getIdconductapostneo() {
		return this.idconductapostneo;
	}

	public void setIdconductapostneo(long idconductapostneo) {
		this.idconductapostneo = idconductapostneo;
	}

	public Consulta getConsulta() {
		return this.consulta;
	}

	public void setConsulta(Consulta consulta) {
		this.consulta = consulta;
	}

	public String getCirugia() {
		return this.cirugia;
	}

	public void setCirugia(String cirugia) {
		this.cirugia = cirugia;
	}

	public String getMilesCilindrico() {
		return this.milesCilindrico;
	}

	public void setMilesCilindrico(String milesCilindrico) {
		this.milesCilindrico = milesCilindrico;
	}

	public String getUrgencia() {
		return this.urgencia;
	}

	public void setUrgencia(String urgencia) {
		this.urgencia = urgencia;
	}

	public Date getUrgenciaFecha() {
		return this.urgenciaFecha;
	}

	public void setUrgenciaFecha(Date urgenciaFecha) {
		this.urgenciaFecha = urgenciaFecha;
	}

	public String getCirujano() {
		return this.cirujano;
	}

	public void setCirujano(String cirujano) {
		this.cirujano = cirujano;
	}

	public String getWS() {
		return this.WS;
	}

	public void setWS(String WS) {
		this.WS = WS;
	}

	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

}
