package com.corecto.web.model.pojo.extra;

// Generated 11-nov-2013 20:22:20 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Consulta generated by hbm2java
 */
public class Consulta implements java.io.Serializable {

	private long idconsulta;
	private CatHospital catHospital;
	private Paciente paciente;
	private String medico;
	private Boolean diaghistologico;
	private Date fecha;
	private Set<AnotomiaPatologica> anotomiaPatologicas = new HashSet<AnotomiaPatologica>(
			0);
	private Set<DescTrataNeo> descTrataNeos = new HashSet<DescTrataNeo>(0);
	private Set<ConductaPostNeo> conductaPostNeos = new HashSet<ConductaPostNeo>(
			0);
	private Set<TratamientoAdyu> tratamientoAdyus = new HashSet<TratamientoAdyu>(
			0);
	private Set<RespuestaTrataNeo> respuestaTrataNeos = new HashSet<RespuestaTrataNeo>(
			0);
	private Set<AnatomiaPatologicaPost> anatomiaPatologicaPosts = new HashSet<AnatomiaPatologicaPost>(
			0);
	private Set<Tratamiento> tratamientos = new HashSet<Tratamiento>(0);
	private Set<Preconsulta> preconsultas = new HashSet<Preconsulta>(0);
	private Set<Antecedentes> antecedenteses = new HashSet<Antecedentes>(0);
	private Set<Estadificacion> estadificacions = new HashSet<Estadificacion>(0);
	private Set<EvaClinica> evaClinicas = new HashSet<EvaClinica>(0);
	private Set<Motivo> motivos = new HashSet<Motivo>(0);
	private Set<ExaProcto> exaProctos = new HashSet<ExaProcto>(0);

	public Consulta() {
	}

	public Consulta(long idconsulta) {
		this.idconsulta = idconsulta;
	}

	public Consulta(long idconsulta, CatHospital catHospital, String medico,
			Boolean diaghistologico, Date fecha,
			Set<AnotomiaPatologica> anotomiaPatologicas,
			Set<DescTrataNeo> descTrataNeos,
			Set<ConductaPostNeo> conductaPostNeos,
			Set<TratamientoAdyu> tratamientoAdyus,
			Set<RespuestaTrataNeo> respuestaTrataNeos,
			Set<AnatomiaPatologicaPost> anatomiaPatologicaPosts,
			Set<Tratamiento> tratamientos, Set<Preconsulta> preconsultas,
			Set<Antecedentes> antecedenteses,
			Set<Estadificacion> estadificacions, Set<EvaClinica> evaClinicas,
			Set<Motivo> motivos, Set<ExaProcto> exaProctos) {
		this.idconsulta = idconsulta;
		this.catHospital = catHospital;
		this.medico = medico;
		this.diaghistologico = diaghistologico;
		this.fecha = fecha;
		this.anotomiaPatologicas = anotomiaPatologicas;
		this.descTrataNeos = descTrataNeos;
		this.conductaPostNeos = conductaPostNeos;
		this.tratamientoAdyus = tratamientoAdyus;
		this.respuestaTrataNeos = respuestaTrataNeos;
		this.anatomiaPatologicaPosts = anatomiaPatologicaPosts;
		this.tratamientos = tratamientos;
		this.preconsultas = preconsultas;
		this.antecedenteses = antecedenteses;
		this.estadificacions = estadificacions;
		this.evaClinicas = evaClinicas;
		this.motivos = motivos;
		this.exaProctos = exaProctos;
	}

	
	public Paciente getPaciente() {
		return paciente;
	}

	public void setPaciente(Paciente paciente) {
		this.paciente = paciente;
	}

	public long getIdconsulta() {
		return this.idconsulta;
	}

	public void setIdconsulta(long idconsulta) {
		this.idconsulta = idconsulta;
	}

	public CatHospital getCatHospital() {
		return this.catHospital;
	}

	public void setCatHospital(CatHospital catHospital) {
		this.catHospital = catHospital;
	}

	public String getMedico() {
		return this.medico;
	}

	public void setMedico(String medico) {
		this.medico = medico;
	}

	public Boolean getDiaghistologico() {
		return this.diaghistologico;
	}

	public void setDiaghistologico(Boolean diaghistologico) {
		this.diaghistologico = diaghistologico;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Set<AnotomiaPatologica> getAnotomiaPatologicas() {
		return this.anotomiaPatologicas;
	}

	public void setAnotomiaPatologicas(
			Set<AnotomiaPatologica> anotomiaPatologicas) {
		this.anotomiaPatologicas = anotomiaPatologicas;
	}

	public Set<DescTrataNeo> getDescTrataNeos() {
		return this.descTrataNeos;
	}

	public void setDescTrataNeos(Set<DescTrataNeo> descTrataNeos) {
		this.descTrataNeos = descTrataNeos;
	}

	public Set<ConductaPostNeo> getConductaPostNeos() {
		return this.conductaPostNeos;
	}

	public void setConductaPostNeos(Set<ConductaPostNeo> conductaPostNeos) {
		this.conductaPostNeos = conductaPostNeos;
	}

	public Set<TratamientoAdyu> getTratamientoAdyus() {
		return this.tratamientoAdyus;
	}

	public void setTratamientoAdyus(Set<TratamientoAdyu> tratamientoAdyus) {
		this.tratamientoAdyus = tratamientoAdyus;
	}

	public Set<RespuestaTrataNeo> getRespuestaTrataNeos() {
		return this.respuestaTrataNeos;
	}

	public void setRespuestaTrataNeos(Set<RespuestaTrataNeo> respuestaTrataNeos) {
		this.respuestaTrataNeos = respuestaTrataNeos;
	}

	public Set<AnatomiaPatologicaPost> getAnatomiaPatologicaPosts() {
		return this.anatomiaPatologicaPosts;
	}

	public void setAnatomiaPatologicaPosts(
			Set<AnatomiaPatologicaPost> anatomiaPatologicaPosts) {
		this.anatomiaPatologicaPosts = anatomiaPatologicaPosts;
	}

	public Set<Tratamiento> getTratamientos() {
		return this.tratamientos;
	}

	public void setTratamientos(Set<Tratamiento> tratamientos) {
		this.tratamientos = tratamientos;
	}

	public Set<Preconsulta> getPreconsultas() {
		return this.preconsultas;
	}

	public void setPreconsultas(Set<Preconsulta> preconsultas) {
		this.preconsultas = preconsultas;
	}

	public Set<Antecedentes> getAntecedenteses() {
		return this.antecedenteses;
	}

	public void setAntecedenteses(Set<Antecedentes> antecedenteses) {
		this.antecedenteses = antecedenteses;
	}

	public Set<Estadificacion> getEstadificacions() {
		return this.estadificacions;
	}

	public void setEstadificacions(Set<Estadificacion> estadificacions) {
		this.estadificacions = estadificacions;
	}

	public Set<EvaClinica> getEvaClinicas() {
		return this.evaClinicas;
	}

	public void setEvaClinicas(Set<EvaClinica> evaClinicas) {
		this.evaClinicas = evaClinicas;
	}

	public Set<Motivo> getMotivos() {
		return this.motivos;
	}

	public void setMotivos(Set<Motivo> motivos) {
		this.motivos = motivos;
	}

	public Set<ExaProcto> getExaProctos() {
		return this.exaProctos;
	}

	public void setExaProctos(Set<ExaProcto> exaProctos) {
		this.exaProctos = exaProctos;
	}

}
