package com.corecto.web.model.pojo.extra;

// Generated 11-nov-2013 20:22:20 by Hibernate Tools 3.4.0.CR1

/**
 * EvaClinica generated by hbm2java
 */
public class EvaClinica implements java.io.Serializable {

	private long idevaclinica;
	private Consulta consulta;
	private String abdomen;
	private String colon;
	private String recto;
	private String adenopatias;
	private String notas;

	public EvaClinica() {
	}

	public EvaClinica(long idevaclinica) {
		this.idevaclinica = idevaclinica;
	}

	public EvaClinica(long idevaclinica, Consulta consulta, String abdomen,
			String colon, String recto, String adenopatias, String notas) {
		this.idevaclinica = idevaclinica;
		this.consulta = consulta;
		this.abdomen = abdomen;
		this.colon = colon;
		this.recto = recto;
		this.adenopatias = adenopatias;
		this.notas = notas;
	}

	public long getIdevaclinica() {
		return this.idevaclinica;
	}

	public void setIdevaclinica(long idevaclinica) {
		this.idevaclinica = idevaclinica;
	}

	public Consulta getConsulta() {
		return this.consulta;
	}

	public void setConsulta(Consulta consulta) {
		this.consulta = consulta;
	}

	public String getAbdomen() {
		return this.abdomen;
	}

	public void setAbdomen(String abdomen) {
		this.abdomen = abdomen;
	}

	public String getColon() {
		return this.colon;
	}

	public void setColon(String colon) {
		this.colon = colon;
	}

	public String getRecto() {
		return this.recto;
	}

	public void setRecto(String recto) {
		this.recto = recto;
	}

	public String getAdenopatias() {
		return this.adenopatias;
	}

	public void setAdenopatias(String adenopatias) {
		this.adenopatias = adenopatias;
	}

	public String getNotas() {
		return this.notas;
	}

	public void setNotas(String notas) {
		this.notas = notas;
	}

}
