package com.corecto.web.model.pojo.extra;

// Generated 11-nov-2013 20:22:20 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ExaProcto generated by hbm2java
 */
public class ExaProcto implements java.io.Serializable {

	private long idexaprocto;
	private Consulta consulta;
	private String tactoRectal;
	private String tactoRectalInfiltra;
	private String rsc;
	private String rscAltura;
	private Date rscFecha;
	private String vcc;
	private String vccAltura;
	private Date vccFecha;
	private Integer ee;
	private Integer eeTipo;
	private Integer eeTipoN;
	private Integer eeInfiltra;
	private Integer eeInfiltraMedida;
	private Date eeFecha;

	public ExaProcto() {
	}

	public ExaProcto(long idexaprocto) {
		this.idexaprocto = idexaprocto;
	}

	public long getIdexaprocto() {
		return this.idexaprocto;
	}

	public void setIdexaprocto(long idexaprocto) {
		this.idexaprocto = idexaprocto;
	}

	public Consulta getConsulta() {
		return this.consulta;
	}

	public void setConsulta(Consulta consulta) {
		this.consulta = consulta;
	}

	public String getTactoRectal() {
		return this.tactoRectal;
	}

	public void setTactoRectal(String tactoRectal) {
		this.tactoRectal = tactoRectal;
	}

	public String getRsc() {
		return this.rsc;
	}

	public void setRsc(String rsc) {
		this.rsc = rsc;
	}

	public String getRscAltura() {
		return this.rscAltura;
	}

	public void setRscAltura(String rscAltura) {
		this.rscAltura = rscAltura;
	}

	public Date getRscFecha() {
		return this.rscFecha;
	}

	public void setRscFecha(Date rscFecha) {
		this.rscFecha = rscFecha;
	}

	public String getVcc() {
		return this.vcc;
	}

	public String getTactoRectalInfiltra() {
		return tactoRectalInfiltra;
	}

	public void setTactoRectalInfiltra(String tactoRectalInfiltra) {
		this.tactoRectalInfiltra = tactoRectalInfiltra;
	}

	public String getVccAltura() {
		return vccAltura;
	}

	public void setVccAltura(String vccAltura) {
		this.vccAltura = vccAltura;
	}

	public Date getVccFecha() {
		return vccFecha;
	}

	public void setVccFecha(Date vccFecha) {
		this.vccFecha = vccFecha;
	}

	public Integer getEe() {
		return ee;
	}

	public void setEe(Integer ee) {
		this.ee = ee;
	}

	public Integer getEeTipo() {
		return eeTipo;
	}

	public void setEeTipo(Integer eeTipo) {
		this.eeTipo = eeTipo;
	}

	public Integer getEeTipoN() {
		return eeTipoN;
	}

	public void setEeTipoN(Integer eeTipoN) {
		this.eeTipoN = eeTipoN;
	}

	public Integer getEeInfiltra() {
		return eeInfiltra;
	}

	public void setEeInfiltra(Integer eeInfiltra) {
		this.eeInfiltra = eeInfiltra;
	}

	public Integer getEeInfiltraMedida() {
		return eeInfiltraMedida;
	}

	public void setEeInfiltraMedida(Integer eeInfiltraMedida) {
		this.eeInfiltraMedida = eeInfiltraMedida;
	}

	public Date getEeFecha() {
		return eeFecha;
	}

	public void setEeFecha(Date eeFecha) {
		this.eeFecha = eeFecha;
	}

	public void setVcc(String vcc) {
		this.vcc = vcc;
	}

}
