package com.corecto.web.model.pojo.extra;

// Generated 11-nov-2013 20:22:20 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ExaProcto generated by hbm2java
 */
public class ExaProcto implements java.io.Serializable {

	private long idexaprocto;
	private Consulta consulta;
	private String tactoRectal;
	private String tactoRectalInfiltra;
	private String rsc;
	private String rscAltura;
	private Date rscFecha;
	private String vcc;
	private String vccAltura;
	private Date vccFecha;
	private String ee;
	private String eeInfiltra;
	private Date eeFecha;

	public ExaProcto() {
	}

	public ExaProcto(long idexaprocto) {
		this.idexaprocto = idexaprocto;
	}

	public ExaProcto(long idexaprocto, Consulta consulta, String tactoRectal,
			String rsc, String rscAltura, Date rscFecha, String vcc,
			String vccAltura, Date vccFecha, String ee, String eeInfiltra,
			Date eeFecha) {
		this.idexaprocto = idexaprocto;
		this.consulta = consulta;
		this.tactoRectal = tactoRectal;
		this.rsc = rsc;
		this.rscAltura = rscAltura;
		this.rscFecha = rscFecha;
		this.vcc = vcc;
		this.vccAltura = vccAltura;
		this.vccFecha = vccFecha;
		this.ee = ee;
		this.eeInfiltra = eeInfiltra;
		this.eeFecha = eeFecha;
	}

	public long getIdexaprocto() {
		return this.idexaprocto;
	}

	public void setIdexaprocto(long idexaprocto) {
		this.idexaprocto = idexaprocto;
	}

	public Consulta getConsulta() {
		return this.consulta;
	}

	public void setConsulta(Consulta consulta) {
		this.consulta = consulta;
	}

	public String getTactoRectal() {
		return this.tactoRectal;
	}

	public void setTactoRectal(String tactoRectal) {
		this.tactoRectal = tactoRectal;
	}

	public String getRsc() {
		return this.rsc;
	}

	public void setRsc(String rsc) {
		this.rsc = rsc;
	}

	public String getRscAltura() {
		return this.rscAltura;
	}

	public void setRscAltura(String rscAltura) {
		this.rscAltura = rscAltura;
	}

	public Date getRscFecha() {
		return this.rscFecha;
	}

	public void setRscFecha(Date rscFecha) {
		this.rscFecha = rscFecha;
	}

	public String getVcc() {
		return this.vcc;
	}

	public void setVcc(String vcc) {
		this.vcc = vcc;
	}

	public String getVccAltura() {
		return this.vccAltura;
	}

	public void setVccAltura(String vccAltura) {
		this.vccAltura = vccAltura;
	}

	public Date getVccFecha() {
		return this.vccFecha;
	}

	public void setVccFecha(Date vccFecha) {
		this.vccFecha = vccFecha;
	}

	public String getEe() {
		return this.ee;
	}

	public void setEe(String ee) {
		this.ee = ee;
	}

	public String getEeInfiltra() {
		return this.eeInfiltra;
	}

	public void setEeInfiltra(String eeInfiltra) {
		this.eeInfiltra = eeInfiltra;
	}

	public Date getEeFecha() {
		return this.eeFecha;
	}

	public void setEeFecha(Date eeFecha) {
		this.eeFecha = eeFecha;
	}

	public String getTactoRectalInfiltra() {
		return tactoRectalInfiltra;
	}

	public void setTactoRectalInfiltra(String tactoRectalInfiltra) {
		this.tactoRectalInfiltra = tactoRectalInfiltra;
	}
	
	

}
