package com.corecto.web.model.pojo.extra;

// Generated 11-nov-2013 20:22:20 by Hibernate Tools 3.4.0.CR1

/**
 * Motivo generated by hbm2java
 */
public class Motivo implements java.io.Serializable {

	private long idmotivo;
	private Consulta consulta;
	private String motivo;
	private byte[] fechaInicio;
	private Integer evoMeses;

	public Motivo() {
	}

	public Motivo(long idmotivo) {
		this.idmotivo = idmotivo;
	}

	public Motivo(long idmotivo, Consulta consulta, String motivo,
			byte[] fechaInicio, Integer evoMeses) {
		this.idmotivo = idmotivo;
		this.consulta = consulta;
		this.motivo = motivo;
		this.fechaInicio = fechaInicio;
		this.evoMeses = evoMeses;
	}

	public long getIdmotivo() {
		return this.idmotivo;
	}

	public void setIdmotivo(long idmotivo) {
		this.idmotivo = idmotivo;
	}

	public Consulta getConsulta() {
		return this.consulta;
	}

	public void setConsulta(Consulta consulta) {
		this.consulta = consulta;
	}

	public String getMotivo() {
		return this.motivo;
	}

	public void setMotivo(String motivo) {
		this.motivo = motivo;
	}

	public byte[] getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(byte[] fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public Integer getEvoMeses() {
		return this.evoMeses;
	}

	public void setEvoMeses(Integer evoMeses) {
		this.evoMeses = evoMeses;
	}

}
