package com.corecto.web.model.pojo.extra;

// Generated 11-nov-2013 20:22:20 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Paciente generated by hbm2java
 */
public class Paciente implements java.io.Serializable {

	private long idpaciente;
	private CatOs catOs;
	private String nombre;
	private String sexo;
	private Date fechanac;
	private String direccion;
	private String localidad;
	private String telefono;
	private String mail;
	private String nroOs;
	private String notas;
	private String dni;
	private Date fechaAgregado;
	private String agregadoPor;
	private Date fechaModificado;
	private String modificadoPor;
	private Set<Consulta> consultas = new HashSet<Consulta>(0);

	public Paciente() {
	}

	public Paciente(long idpaciente) {
		this.idpaciente = idpaciente;
	}

	public long getIdpaciente() {
		return this.idpaciente;
	}

	public void setIdpaciente(long idpaciente) {
		this.idpaciente = idpaciente;
	}

	public CatOs getCatOs() {
		return this.catOs;
	}

	public void setCatOs(CatOs catOs) {
		this.catOs = catOs;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getSexo() {
		return this.sexo;
	}

	public void setSexo(String sexo) {
		this.sexo = sexo;
	}

	public Date getFechanac() {
		return this.fechanac;
	}

	public void setFechanac(Date fechanac) {
		this.fechanac = fechanac;
	}

	public String getDireccion() {
		return direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getLocalidad() {
		return localidad;
	}

	public void setLocalidad(String localidad) {
		this.localidad = localidad;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	public String getNroOs() {
		return this.nroOs;
	}

	public void setNroOs(String nroOs) {
		this.nroOs = nroOs;
	}

	public String getNotas() {
		return this.notas;
	}

	public void setNotas(String notas) {
		this.notas = notas;
	}

	public Set<Consulta> getConsultas() {
		return consultas;
	}

	public void setConsultas(Set<Consulta> consultas) {
		this.consultas = consultas;
	}

	public String getDni() {
		return dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public Date getFechaAgregado() {
		return fechaAgregado;
	}

	public void setFechaAgregado(Date fechaAgregado) {
		this.fechaAgregado = fechaAgregado;
	}

	public String getAgregadoPor() {
		return agregadoPor;
	}

	public void setAgregadoPor(String agregadoPor) {
		this.agregadoPor = agregadoPor;
	}

	public Date getFechaModificado() {
		return fechaModificado;
	}

	public void setFechaModificado(Date fechaModificado) {
		this.fechaModificado = fechaModificado;
	}

	public String getModificadoPor() {
		return modificadoPor;
	}

	public void setModificadoPor(String modificadoPor) {
		this.modificadoPor = modificadoPor;
	}

}
