package com.corecto.web.model.pojo.extra;

// Generated 11-nov-2013 20:22:20 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Paciente generated by hbm2java
 */
public class Paciente implements java.io.Serializable {

	private long idpaciente;
	private CatOs catOs;
	private String nombre;
	private String sexo;
	private Date fechanac;
	private String domicilio;
	private String telefono;
	private String mail;
	private String nroOs;
	private String notas;
	private Set<Consulta> consultas = new HashSet<Consulta>(0);

	public Paciente() {
	}

	public Paciente(long idpaciente) {
		this.idpaciente = idpaciente;
	}

	public Paciente(long idpaciente, CatOs catOs, String nombre, String sexo,
			Date fechanac, String domicilio, String telefono, String mail,
			String nroOs, String notas) {
		this.idpaciente = idpaciente;
		this.catOs = catOs;
		this.nombre = nombre;
		this.sexo = sexo;
		this.fechanac = fechanac;
		this.domicilio = domicilio;
		this.telefono = telefono;
		this.mail = mail;
		this.nroOs = nroOs;
		this.notas = notas;
	}

	public long getIdpaciente() {
		return this.idpaciente;
	}

	public void setIdpaciente(long idpaciente) {
		this.idpaciente = idpaciente;
	}

	public CatOs getCatOs() {
		return this.catOs;
	}

	public void setCatOs(CatOs catOs) {
		this.catOs = catOs;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getSexo() {
		return this.sexo;
	}

	public void setSexo(String sexo) {
		this.sexo = sexo;
	}

	public Date getFechanac() {
		return this.fechanac;
	}

	public void setFechanac(Date fechanac) {
		this.fechanac = fechanac;
	}

	public String getDomicilio() {
		return this.domicilio;
	}

	public void setDomicilio(String domicilio) {
		this.domicilio = domicilio;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	public String getNroOs() {
		return this.nroOs;
	}

	public void setNroOs(String nroOs) {
		this.nroOs = nroOs;
	}

	public String getNotas() {
		return this.notas;
	}

	public void setNotas(String notas) {
		this.notas = notas;
	}

	public Set<Consulta> getConsultas() {
		return consultas;
	}

	public void setConsultas(Set<Consulta> consultas) {
		this.consultas = consultas;
	}

	
}
