package com.corecto.web.model.pojo.extra;

// Generated 11-nov-2013 20:22:20 by Hibernate Tools 3.4.0.CR1

/**
 * Preconsulta generated by hbm2java
 */
public class Preconsulta implements java.io.Serializable {

	private long idpreconsulta;
	private Consulta consulta;
	private Double peso;
	private Double talla;
	private Double supcorporal;
	private String performanceStatus;
	private String comentario;

	public Preconsulta() {
	}

	public Preconsulta(long idpreconsulta) {
		this.idpreconsulta = idpreconsulta;
	}

	public Preconsulta(long idpreconsulta, Consulta consulta, Double peso,
			Double talla, Double supcorporal, String performanceStatus,
			String comentario) {
		this.idpreconsulta = idpreconsulta;
		this.consulta = consulta;
		this.peso = peso;
		this.talla = talla;
		this.supcorporal = supcorporal;
		this.performanceStatus = performanceStatus;
		this.comentario = comentario;
	}

	public long getIdpreconsulta() {
		return this.idpreconsulta;
	}

	public void setIdpreconsulta(long idpreconsulta) {
		this.idpreconsulta = idpreconsulta;
	}

	public Consulta getConsulta() {
		return this.consulta;
	}

	public void setConsulta(Consulta consulta) {
		this.consulta = consulta;
	}

	public Double getPeso() {
		return this.peso;
	}

	public void setPeso(Double peso) {
		this.peso = peso;
	}

	public Double getTalla() {
		return this.talla;
	}

	public void setTalla(Double talla) {
		this.talla = talla;
	}

	public Double getSupcorporal() {
		return this.supcorporal;
	}

	public void setSupcorporal(Double supcorporal) {
		this.supcorporal = supcorporal;
	}

	public String getPerformanceStatus() {
		return this.performanceStatus;
	}

	public void setPerformanceStatus(String performanceStatus) {
		this.performanceStatus = performanceStatus;
	}

	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

}
