package com.corecto.web.model.pojo.extra;

// Generated 11-nov-2013 20:22:20 by Hibernate Tools 3.4.0.CR1

/**
 * Tratamiento generated by hbm2java
 */
public class Tratamiento implements java.io.Serializable {

	private long idtratamiento;
	private Consulta consulta;
	private String udaondo;
	private String cirugia;
	private String quimioterapiaInduc;
	private String quimi0teInducNroCiclos;
	private String quimioOtra;
	private String quimioterapiaInter;
	private String quimi0teInterNroCiclos;

	public Tratamiento() {
	}

	public Tratamiento(long idtratamiento) {
		this.idtratamiento = idtratamiento;
	}

	public Tratamiento(long idtratamiento, Consulta consulta, String udaondo,
			String cirugia, String quimioterapiaInduc,
			String quimi0teInducNroCiclos, String quimioOtra,
			String quimioterapiaInter, String quimi0teInterNroCiclos) {
		this.idtratamiento = idtratamiento;
		this.consulta = consulta;
		this.udaondo = udaondo;
		this.cirugia = cirugia;
		this.quimioterapiaInduc = quimioterapiaInduc;
		this.quimi0teInducNroCiclos = quimi0teInducNroCiclos;
		this.quimioOtra = quimioOtra;
		this.quimioterapiaInter = quimioterapiaInter;
		this.quimi0teInterNroCiclos = quimi0teInterNroCiclos;
	}

	public long getIdtratamiento() {
		return this.idtratamiento;
	}

	public void setIdtratamiento(long idtratamiento) {
		this.idtratamiento = idtratamiento;
	}

	public Consulta getConsulta() {
		return this.consulta;
	}

	public void setConsulta(Consulta consulta) {
		this.consulta = consulta;
	}

	public String getUdaondo() {
		return this.udaondo;
	}

	public void setUdaondo(String udaondo) {
		this.udaondo = udaondo;
	}

	public String getCirugia() {
		return this.cirugia;
	}

	public void setCirugia(String cirugia) {
		this.cirugia = cirugia;
	}

	public String getQuimioterapiaInduc() {
		return this.quimioterapiaInduc;
	}

	public void setQuimioterapiaInduc(String quimioterapiaInduc) {
		this.quimioterapiaInduc = quimioterapiaInduc;
	}

	public String getQuimi0teInducNroCiclos() {
		return this.quimi0teInducNroCiclos;
	}

	public void setQuimi0teInducNroCiclos(String quimi0teInducNroCiclos) {
		this.quimi0teInducNroCiclos = quimi0teInducNroCiclos;
	}

	public String getQuimioOtra() {
		return this.quimioOtra;
	}

	public void setQuimioOtra(String quimioOtra) {
		this.quimioOtra = quimioOtra;
	}

	public String getQuimioterapiaInter() {
		return this.quimioterapiaInter;
	}

	public void setQuimioterapiaInter(String quimioterapiaInter) {
		this.quimioterapiaInter = quimioterapiaInter;
	}

	public String getQuimi0teInterNroCiclos() {
		return this.quimi0teInterNroCiclos;
	}

	public void setQuimi0teInterNroCiclos(String quimi0teInterNroCiclos) {
		this.quimi0teInterNroCiclos = quimi0teInterNroCiclos;
	}

}
